name: Jekyll Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/jekyll-build-pages@v1.0.13
        with:
          source: docs
          destination: ./docs/.site
